version: '3.8'

services:
  web:
    image: php:5.6-apache # Use the specific PHP 5.6 Apache image
    container_name: hack2015_apache
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    volumes:
      - ./php_code:/var/www/html # Mount your local PHP code directory to the web root
    networks:
      - hack2015

  database:
    image: mysql:5.7 # Use a compatible MySQL version
    container_name: hack2015_db
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword123 # Set the root password
      MYSQL_DATABASE: jobs # Set a default database name
    volumes:
      - db:/var/lib/mysql # Persist database data in a volume
    networks:
      - hack2015


networks:
  hack2015:
    driver: bridge
